#!/bin/bash

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

CONFIG_FILE='/etc/openldap/slapd.conf'

# File containing recognized CA certs:
: ${CA_CERT_PATH:-/etc/ssl/certs} && \
sed -i "s|XXX-CA_CERT_PATH-XXX|${CA_CERT_PATH}|" ${CONFIG_FILE}

# Slapd server certificate:
: ${CERT_FILE:-/etc/ssl/certs} && \
sed -i "s|XXX-CERT_FILE-XXX|${CERT_FILE}|" ${CONFIG_FILE}

# Slapd server private key:
: ${CERT_KEY_FILE:-/etc/ssl/certs} && \
sed -i "s|XXX-CERT_KEY_FILE-XXX|${CERT_KEY_FILE}|" ${CONFIG_FILE}

# Upstream LDAP server URI:
: ${LDAP_UPSTREAM_URI:-ldaps://127.0.0.1:636} && \
sed -i "s|XXX-LDAP_UPSTREAM_URI-XXX|${LDAP_UPSTREAM_URI}|" ${CONFIG_FILE}

# Upstream LDAP server suffix:
: ${LDAP_UPSTREAM_SUFFIX:-''} && \
sed -i "s/XXX-LDAP_UPSTREAM_SUFFIX-XXX/${LDAP_UPSTREAM_SUFFIX}/" ${CONFIG_FILE}

#-----------------------------------------------------------------------------
# Run:
#-----------------------------------------------------------------------------

cat ${CONFIG_FILE}
export SSL_CERT_DIR=${SSL_CERT_DIR:-/certs} && c_rehash ${SSL_CERT_DIR}
slaptest -f ${CONFIG_FILE} && exec env slapd -d 2 -h "ldap:/// ldaps:///"
